### PR TITLE
Fixed error while unlocking using complex passwords

### PR DESCRIPTION
**Pull request by ghost**
Present master version fails when using passwords that start by '-' (i.e.). I would expect it to fail with others.

### CODE REVIEW

**Review by Mange — APPROVED** [review]
This makes a lot of sense. It would also prevent the password from being visible on the process list, which is also a plus.

Disclaimer: I have not tried the code. This is only a review from my phone.

**Comment by mattydebie** [comment]
Good finding! This indeed fails on passwords starting with `-` (bash sees arguments starting with `-` as options in stead of arguments). Another fix would have been 
`bw unlock -- "$mpw"`
@Mange I'm not sure what you mean by the password not being visible in the process list? Piping or not, will that not be visible as a process?

**Comment by Mange** [comment]
`echo` is a built-in command in the shell so it won't show up in the process list.

**Comment by mattydebie** [comment]
Alright, awesome!

**Comment by mattydebie** [comment]
@Mange Would you mind releasing this to AUR? (version 0.3)

**Comment by Mange** [comment]
[Done!](https://aur.archlinux.org/cgit/aur.git/commit/?h=bitwarden-rofi&id=d94454bf928c9500f96a02509a9d29a40bac6a06)

**Pull request merged**
